# Alacritty configuration for Catppuccin Mocha theme

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

# Optional: set size
size = 12.0

[colors]
# Default colors
primary = { background = "#1e1e2e", foreground = "#d9e0ee" }

  # Normal colors
  [colors.normal]
  black   = "#1e1e2e"
  red     = "#e78284"
  green   = "#a6d189"
  yellow  = "#e5c890"
  blue    = "#8caaee"
  magenta = "#f4b8e4"
  cyan    = "#89dceb"
  white   = "#d9e0ee"

  # Bright colors
  [colors.bright]
  black   = "#2a273f"
  red     = "#e78284"
  green   = "#a6d189"
  yellow  = "#e5c890"
  blue    = "#8caaee"
  magenta = "#f4b8e4"
  cyan    = "#89dceb"
  white   = "#f5e0dc"

  # Cursor colors
  [colors.cursor]
  text = "#1e1e2e"
  cursor = "#f5e0dc"

  [colors.selection]
  text = "#1e1e2e"
  background = "#f5e0dc"

[window]
padding = { x = 10, y = 10 }
dynamic_title = true

[cursor]
style = "Block"  # Cursor style
