# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt beep extendedglob
unsetopt autocd notify
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/stake/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Start tmux automatically if not already inside a tmux session
if [ -z "$TMUX" ]; then
    tmux
fi

source ~/.zsh_profile
