# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt beep extendedglob
unsetopt autocd notify
bindkey -e
# End of lines configured by zsh-newuser-install

# The following lines were added by compinstall

zstyle ':completion:*' verbose true
zstyle :compinstall filename '/home/stake/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Start starship if not already started
eval "$(starship init zsh)"

# add scripts folder to my profile
export PATH="$HOME/.scripts:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# add nvm to my profile
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

# Exit the shell if tmux exits
if [ -z "$TMUX" ]; then
  tmux attach-session -t main || tmux new-session -s main
  exit  # <-- This closes the shell after tmux exits
fi

# source my information
source ~/.zshenv
source ~/.zsh_profile
